# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sensor_event.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'sensor_event.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12sensor_event.proto\x12\x06sensor\"$\n\x08Location\x12\x0b\n\x03lat\x18\x01 \x01(\x01\x12\x0b\n\x03lon\x18\x02 \x01(\x01\"l\n\x06\x44\x65vice\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x11\n\tsensor_id\x18\x02 \x01(\t\x12\x18\n\x10\x66irmware_version\x18\x03 \x01(\t\x12\"\n\x08location\x18\x04 \x01(\x0b\x32\x10.sensor.Location\"<\n\x05Trace\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x10\n\x08trace_id\x18\x02 \x01(\t\x12\x0f\n\x07span_id\x18\x03 \x01(\t\";\n\x0f\x43hannelMetadata\x12\x0f\n\x07spiking\x18\x01 \x01(\x08\x12\x17\n\x0f\x61lert_threshold\x18\x02 \x01(\x01\")\n\x0eSimulationInfo\x12\x17\n\x0fsimulation_type\x18\x01 \x01(\t\"\x9c\x03\n\x0bSensorEvent\x12\x13\n\x0boccurred_at\x18\x01 \x01(\x03\x12\x13\n\x0bingested_at\x18\x02 \x01(\x03\x12\x1e\n\x06\x64\x65vice\x18\x03 \x01(\x0b\x32\x0e.sensor.Device\x12+\n\x04\x64\x61ta\x18\x04 \x03(\x0b\x32\x1d.sensor.SensorEvent.DataEntry\x12\x33\n\x08\x63hannels\x18\x05 \x03(\x0b\x32!.sensor.SensorEvent.ChannelsEntry\x12\x1c\n\x05trace\x18\x06 \x01(\x0b\x32\r.sensor.Trace\x12\x0c\n\x04tags\x18\x07 \x03(\t\x12/\n\nsimulation\x18\x08 \x01(\x0b\x32\x16.sensor.SimulationInfoH\x00\x88\x01\x01\x1a+\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\x1aH\n\rChannelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12&\n\x05value\x18\x02 \x01(\x0b\x32\x17.sensor.ChannelMetadata:\x02\x38\x01\x42\r\n\x0b_simulationb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sensor_event_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENSOREVENT_DATAENTRY']._loaded_options = None
  _globals['_SENSOREVENT_DATAENTRY']._serialized_options = b'8\001'
  _globals['_SENSOREVENT_CHANNELSENTRY']._loaded_options = None
  _globals['_SENSOREVENT_CHANNELSENTRY']._serialized_options = b'8\001'
  _globals['_LOCATION']._serialized_start=30
  _globals['_LOCATION']._serialized_end=66
  _globals['_DEVICE']._serialized_start=68
  _globals['_DEVICE']._serialized_end=176
  _globals['_TRACE']._serialized_start=178
  _globals['_TRACE']._serialized_end=238
  _globals['_CHANNELMETADATA']._serialized_start=240
  _globals['_CHANNELMETADATA']._serialized_end=299
  _globals['_SIMULATIONINFO']._serialized_start=301
  _globals['_SIMULATIONINFO']._serialized_end=342
  _globals['_SENSOREVENT']._serialized_start=345
  _globals['_SENSOREVENT']._serialized_end=757
  _globals['_SENSOREVENT_DATAENTRY']._serialized_start=625
  _globals['_SENSOREVENT_DATAENTRY']._serialized_end=668
  _globals['_SENSOREVENT_CHANNELSENTRY']._serialized_start=670
  _globals['_SENSOREVENT_CHANNELSENTRY']._serialized_end=742
# @@protoc_insertion_point(module_scope)
